### ISSUE TITLE
Is the JSON file being updated 

### ISSUE THREAD

**Issue by sagaya** [phanirithvij/twist.moe#17]
I saw the JSON file in the documentation https://raw.githubusercontent.com/phanirithvij/Myanimewebsite/master/twistlinks.json i just want to know if this file is being updated with the latest twist.moe anime's and episodes, this will be very useful.

**Comment by phanirithvij** [comment]
No it's not up to date. I lost the code to generate it. I keep forgetting about it. I will update it soon.
Please remind me by adding a comment here when you read this.

**Comment by sagaya** [comment]
Okay, please update it thank you. Also if you could explain how you generated it, it will be so helpful

**Comment by sagaya** [comment]
Hi, please are don't forget to update the JSON file.

**Comment by phanirithvij** [comment]
I did it.
Do a `git pull` and then,
```shell
python allanime.py filename.json # the filename to save
```

**Comment by phanirithvij** [comment]
Close this issue if it works.

**Comment by sagaya** [comment]
The format of the output json is different from the one in the REAMDE

**Comment by sagaya** [comment]
It will be really helpful if you can format it like the README one, i already started using it in a script and i have downloaded close to 1,000 animes don't want to have to start all over again.

**Comment by phanirithvij2000** [comment]
You can write a script to change the json to that format pretty easily.

**Comment by sagaya** [comment]
Thank you.

**Comment by vivian-ng** [comment]
Sorry to bring this up on a closed thread, but I got this error when using `python3 allanime.py filename.json`

```
Reading from "data.json" and storing in "filename.json"
[>] Requesting Site
[*] Status Code:  200
[*] Content Length: 3415
Traceback (most recent call last):
  File "allanime.py", line 217, in <module>
    data = get_names_json(datafile)
  File "allanime.py", line 86, in get_names_json
    ret = {'total': len(ul), 'data': [], 'created': str(datetime.now())}
TypeError: object of type 'NoneType' has no len()
```

Any idea how to solve it?

**Comment by phanirithvij** [comment]
@vivian-ng I'm not in a place where there's a good network so I need some time to take a look at this. But I will. Please remind me in 2 days if possible.

**Comment by vivian-ng** [comment]
@phanirithvij Thanks for taking time to look into this issue.

**Comment by vivian-ng** [comment]
@phanirithvij `python3 allanime.py filename.json` still gives the same error, if you can share information on how the JSON file is requested and built, I can try to find out what is the problem.

**Comment by phanirithvij** [comment]
@vivian-ng sorry I forgot to reply here, check the new `allanimenew.py` file, but note that for now, it only fetches the anime info from their API link. ~Episode links are NOT queried.~ implemented

**Comment by phanirithvij** [comment]
@vivian-ng Also the json format is different from the previous version, and if you need backward compatibility like OP you can write a simple script to convert it.

**Comment by vivian-ng** [comment]
@phanirithvij Thank you for solving it. The script now uses the fixed output file `new.json` and `new.min.json` even if a filename is specified as an argument. But at least it can download the json file now. Hurray!
